# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/tracoor.yaml.j2
tracoor-single:
  fullnameOverride: "tracoor"
  image:
    repository: docker.ethquokkaops.io/dh/ethpandaops/tracoor
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  ingress:
    http:
      enabled: true
      className: ingress-nginx-public
      hosts:
        - host: tracoor.stefan-devnet-0.ethpandaops.io
          paths:
            - path: /
              pathType: Prefix

  postgresql:
    enabled: true
    fullnameOverride: "tracoor-postgresql"
    auth:
      username: <path:/secrets/services/services.enc.yaml#tracoor | jsonPath {.postgres.devnets.username}>
      password: <path:/secrets/services/services.enc.yaml#tracoor | jsonPath {.postgres.devnets.password}>
    primary:
      persistence:
        enabled: true
        size: 20Gi
      resources:
        requests:
          cpu: 1000m
          memory: 2Gi
        limits:
          cpu: 2000m
          memory: 4Gi

  config:
    shared:
      metricsAddr: ":9091"
      logging: "debug"
      indexer:
        address: localhost:8081
      store:
        type: s3
        config:
          region: us-east-1
          bucket_name: stefan-devnet-0/tracoor
          endpoint: https://<path:/secrets/services/services.enc.yaml#cloudflare | jsonPath {.account_ids.ethdevops}>.r2.cloudflarestorage.com/ethpandaops-devnet-dumpster
          prefer_urls: true
          access_key: <path:/secrets/services/services.enc.yaml#cloudflare | jsonPath {.r2.devnets.access_key_id}>
          access_secret: <path:/secrets/services/services.enc.yaml#cloudflare | jsonPath {.r2.devnets.secret_access_key}>

    server:
      addr: ":8081"
      gatewayAddr: ":8080"
      pprofAddr: ":6060"
      preStopSleepSeconds: 1
      ntpServer: time.google.com
      persistence: {}
      services:
        indexer:
          retention:
            beaconStates: 100h
            executionBlockTraces: 100h
            beaconBlocks: 100h
      ethereum:
        config:
          repository: ethpandaops/stefan-devnets
          branch: master
          path: network-configs/devnet-0/metadata
        tools:
          ncli:
            repository: docker.ethquokkaops.io/dh/status-im/nimbus-eth2
            branch: unstable
          lcli:
            repository: docker.ethquokkaops.io/dh/ethpandaops/lighthouse
            branch: unstable
          zcli:
            fork: electra

    agents:
      - name: bootnode-1
        ethereum:
          overrideNetworkName: stefan-devnet-0
          beacon:
            nodeAddress: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.stefan-devnets.node_ingress.combined}>@bn-bootnode-1.srv.stefan-devnet-0.ethpandaops.io
          execution:
            nodeAddress: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.stefan-devnets.node_ingress.combined}>@rpc-bootnode-1.srv.stefan-devnet-0.ethpandaops.io
            traceDisableMemory: true
            traceDisableStack: true
            traceDisableStorage: true
      - name: lighthouse-geth-full-1
        ethereum:
          overrideNetworkName: stefan-devnet-0
          beacon:
            nodeAddress: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.stefan-devnets.node_ingress.combined}>@bn-lighthouse-geth-full-1.srv.stefan-devnet-0.ethpandaops.io
          execution:
            nodeAddress: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.stefan-devnets.node_ingress.combined}>@rpc-lighthouse-geth-full-1.srv.stefan-devnet-0.ethpandaops.io
            traceDisableMemory: true
            traceDisableStack: true
            traceDisableStorage: true
      - name: lighthouse-geth-super-1
        ethereum:
          overrideNetworkName: stefan-devnet-0
          beacon:
            nodeAddress: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.stefan-devnets.node_ingress.combined}>@bn-lighthouse-geth-super-1.srv.stefan-devnet-0.ethpandaops.io
          execution:
            nodeAddress: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.stefan-devnets.node_ingress.combined}>@rpc-lighthouse-geth-super-1.srv.stefan-devnet-0.ethpandaops.io
            traceDisableMemory: true
            traceDisableStack: true
            traceDisableStorage: true
