name: Install deps
description: Install deps
runs:
  using: composite
  steps:
    - name: Install asdf
      uses: asdf-vm/actions/setup@v3

    - name: Install asdf tools
      shell: bash
      run: ./setup.sh
