secret_zerossl:
    ACME_EAB_KID: ENC[AES256_GCM,data:Gg5E8yH+1Q==,iv:hGQ5GGezb+TNZ7jU3RsRWu0o4wIDNPmNV4J4fAp2BSw=,tag:6nY9DJ+QJEfCGBsx3FNgUQ==,type:str]
    ACME_EAB_HMAC_KEY: ENC[AES256_GCM,data:A3v0MxxygA==,iv:qsI0dp2cNVEHgqvFUKiOM542pjG7ZbzHexSXprMBw2E=,tag:Y7xsvVwRV7PQurO7QeNiWw==,type:str]
secret_prometheus_remote_write:
    username: ENC[AES256_GCM,data:zpGvEsv1Lrk=,iv:OVx9miE7xFRL/rBM6dkc+hnBYqPuRJTWhhzQ4T/hsmU=,tag:o+ulpT+Hxx8pmp7O6YPdlw==,type:str]
    password: ENC[AES256_GCM,data:14dBuUrGzQ==,iv:sOc8R7kQ0mxeUxTkjVIBCKhr+lvE7W2i3xfkmFlHj4U=,tag:1GhjGilrb32jr4wFVMXZ1w==,type:str]
secret_nginx_shared_basic_auth:
    name: ENC[AES256_GCM,data:bjlM,iv:DiOGlqfOfrDlt7X4OGY27OYlkDDEHguv+kg1zRhBek0=,tag:ZPlucwl2PNXeXcOc8PmCBQ==,type:str]
    password: ENC[AES256_GCM,data:NdtJvQ==,iv:qTDUrwmpKeh0yJB+GlJO7eZ2w0GHn8Lhu6wPS9Twc/g=,tag:QRtMmdNUCmm8XNjPQjqSnQ==,type:str]
secret_ethstats: ENC[AES256_GCM,data:WooVcg7hnyw=,iv:oChffj5kkh5901EC995UMnY8QmQAZtCycuHuF895vfU=,tag:WgwJwBjqYR/5d4cjukuM/A==,type:str]
secret_xatu_sentry:
    server_address: ENC[AES256_GCM,data:1ZzqPJR2ahKnEf79n5lJG+s8kWjPLNnj4pfC9Bep,iv:c+BAgvsoj0D1GP3X7W2KAw+vpE2jf/K8pFiMnxaYd2A=,tag:5OeZLGNhaACttaRIRvMNYA==,type:str]
    user: ENC[AES256_GCM,data:6Rl/PXMHqw==,iv:gHXmk6tie0m6usKO6v9kwBI3BW0Kjj04wuMiijQYVbg=,tag:qjLt4uzXQ2s3j+xvEGlYFQ==,type:str]
    password: ENC[AES256_GCM,data:IXDXoO92,iv:vqjxnUIH2pso34k6DJTH8/ixkWgfrqb1TDqHslMj+6M=,tag:Jh8HaOMD9XSK1v4bouZHew==,type:str]
secret_genesis_mnemonic: ENC[AES256_GCM,data:23GmxqsbgvBVxqzp3dV8FlhAO7u3PKMP2FnP2lbk/tmjHQ6k7SHOnitqyWhJvyBjDVdofI4B0cw+0jVtvdnA6akuamfiT1qasZEZCpsQt78HnDa7VSBWeMEkyJgaRMaiG+uCsMbEZ/OX5O7JoIYDx9+QZss1zGu4dX5soTWpto+hUf2o9Nfm7Alp4go53iuxoipdsDeKCkyHegozLP2DdA==,iv:9X2DYpWHroJMFRS2FXos5gIVdybLdRiLi6RYoYnRhx8=,tag:h+EIIeNpzw34ro5lzcSggw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-28T10:43:00Z"
    mac: ENC[AES256_GCM,data:agACOTRVinIESg+Oi9OJcLALc53CWaYbQJzYNjqg+TV1eK6D1dj60q2T7NUhgOvjqNIy+B0Br1Mj+hRvBswS8FZVdxI+31c8OKAfe8qqc4w1lH/wi1JhlwPJB17mrvTUlBxhiML+CamZobOpHjkq6YL0mGXQ4/Zx3IgtvOhDDnM=,iv:pkFJoT3w/P3xOfwvXE0sXZkROdEX6gKyJbLDK8smHhs=,tag:Heafk8STyhWdR9G2OUOlcw==,type:str]
    pgp:
        - created_at: "2023-02-02T11:09:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA32GcoRiZf6pAQ//fs8kSUDmQsCVDJMfS4nLunRNvad9axIj9k3P1qgePEhl
            Mj3rB9Zq6DmQxz8fHLu23zMS8bMEEKPYdNSbL0uM+K+2auLXCCQIex8+7rOMpn8m
            WjlQr01QCTTdlp5JIkgFcO1zEUNw8cra9Pqm07D0SA2Tsdok9NME1pNkMkZhla/e
            v+/X+aB8NzOsu+z7jeLW7ZRpWR2pBZjIujT+LnW/9rY4XPHKeuetERblv/OlXzBR
            KnuNJE/21/J5cVD6umkNWvy1tWtgkKlHpY9F/Cd3P0eXO+xbKhu612PLTK1ts5NA
            qCyiVpr2IiuCDycqvByrBArXScKOC1VrO6NFfTs2mVjJUNlO83TdnFnQhPjnRXK9
            roC1sas5ZUflgxrrjHWr5avY+vQpAYrQBhy5mM5iaiyG4KPvbmsvig7nViaJg3tY
            nIvdxtFo2cf9vDud86Ea324GYLF+vS14W+yBbWjOrXm1hc2oQP44qCJmX7DMw3eS
            sGIpiEQSXX8Bhe+v/LdPOR8K8iGzEGrowjAYYL97C0KE3fh9/9ZwrENs58J+FLHP
            4I5ec/YxJ1scOZ7EaJFMgjguRZ3pnNlnWqz6Fn2mD7uaLRMEtzXk1ktZtrWEja5d
            jBtjFyfhbmSftPShCSnRroFPBHDrsTB5fM2yLgf7i82EtvLPJQbv5RYUO9ap93XS
            UQGeO25IZ0KP5C0lLl564vZmNzG4qHgh8ho/vJOXhr+rLhhNpBuf7KLUgMOHHmy1
            FDG4sNHY3Ipq7UKwjxo7VN3ywKXs7OlM0C5GgfjT+LIGHA==
            =+wWs
            -----END PGP MESSAGE-----
          fp: 80DB2B4EF6CA4D9829C280605636BC0E08138A24
        - created_at: "2023-02-02T11:09:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA87Wber4r4dGARAAhBKCiSKc7BCFJgxDSzVzquzo2WXXotef5p6xF+NDxUh7
            A0DGgbGDNrhumof7Q+CwF7D6WjCt5xA6ZNqfaMAaWUSbSIa7TeCivbml65GJg9kl
            O1w5c90pWDoowAIcN32Eec11sZA5gpuKbXhAMYgbA4TxPuz9QTOV3ZV0Oie9u3hA
            hGjZtR4GP/CWAcMrUbaX4o6BmCuClaXtz1U+iVdj40WJej7G4MEgCY2b/PMlIjhG
            gIcr4Tz5nV5Tvn074t50Y5j+0zAmwmITmyA7avZhbNnrYTqunIk0mXsvN9dd2TGM
            ULY3RqUiOeJPu/Nh4F2WV0dYhQwwvGUw4ilHSauYbjImGU5lsBrseqGxNFIOSnXs
            ro4be5gygPPWbwGlAZzazz8btjkEyD+6FI8iT4/AfUhUMvPWJNB1hArlhkcQwfqx
            aSppxzW+ZhZYeAGx6OslUQgrutrW34N6gqHljQfKCTpa/LAnTiBqE0SaCV7ikCUV
            ePUyPzEb0kLBGT10l5d1PVsHuUPy93jlFymt8E/KF7zdJylnYLv3nZQaWzXH6Bvz
            uDL6VE9G/XOs4rnGj95tZcUDhcl8jSZr0a6syp2i4z8+U4n17+p0J0voGayL52S9
            2gR815wLcj2Ombhpsvan8HmCzxZ22YZtKFM5H5iotliMMLSaKvGewzH0cZSjY67S
            UQE9J/dBHdQCRGkSbVO0kJYCznv7z/n7KiaGD0ocd3uWihKCZAtVPQCiswttUr4a
            kRQV3Tit/3o+e5w6/FrffdB6fKHB0XQJerf/W6lsdUHAbA==
            =Wg0P
            -----END PGP MESSAGE-----
          fp: 69F66EEA7AE36CCB77DDB8CA1BC39532FB4A2DBD
        - created_at: "2023-02-02T11:09:14Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4hw3nPn82LyARAAl2V71kk5JQmzNnhiyriLn9Q3CF8w+zUJBEFF1TeskyDt
            gt4E7ofRRS5IWmnwPnxcaVvzU6RvLNMmZPgc/l+2iF4+T0e3jqfvu6cygEISg6B7
            p+3QBcaQKlw1sbSDIuczYGU/tZxRdpwlS2D8+p8RSbHOJtldYx6k4LoF/lNgmO5c
            kr2+AbAM3SSB5ddR4EZ77wCxn2xZrd4h1jo18KWToB4yvLHpJzHSvz26JMlWph83
            LqZzw7vKKq4AB8641d6zULZ0QGp0Y3aSY5hFcTOlXrxoevnT6iwY5scHVdXrC3MJ
            kLHJ7vWO3xybzLDKKhh0QkHuKUH5TviuEAWOgffx+H8sLOnAA+4NeYbECL7lw3Lv
            KiHtRxQggdrjJi1KgZ0evAAR8fhrJjT6uj9BKpZMUQd8FXXeZwoeo3HhCz/ZHYKq
            boSX2NZgj2WMpxIstuIywa+w3KfzJc37xXYsZKslT9yYoErL8zIv6xpHE9Kh2noT
            sM4m74J8SDsHaIZb/zJ3G0HJ2i5iCVKwBQyvrsJXJ3kG1YYf5E+WAwwXcRAOrcNW
            mFX43/ICgG5jPwy34rbkNeU/a7+rJsi6SMtAl9C+//lXY/nvCjHCg7ky5dfx2dkw
            46IhWSKhzAVywJRWUvWJQYNWNGVw1VYMu2dhWGsUxgT+Sk8aBGCWJntxfcIsAZDS
            UQF95D0nwXAh/R0Wy8lcw5zot+vpX0VzrK/t9swiqJmTlTRE29ut9LiMRyvKRllu
            Ug9p4eszd9H2X9RLMkJOBniW/vrdoNfTAQ3Y47XZYppceg==
            =LgKk
            -----END PGP MESSAGE-----
          fp: D1002590180DE371BCB455EAEFCD4ACD0B4D3F6E
        - created_at: "2023-02-02T11:09:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMAw01qfIBwY0JARAAkQpoz+txax/3wWkQ/eWKHszY3CLTpjD7AyJDkRvM94wZ
            UH32WYQCTeDzbT+z7TPw89riXvwFf9F46FcBJ3dCh7iMyhYmqAtKMl9FhIXXtZzp
            n3l1fYjKZ5fDP2z8qA4KKRD35V5wWn4lNtJdwsv1OxlFvgr7xNB39VVKE/kXm8VN
            yO4xCFz7TAasVj24D2zpo59i/WkV9uepZZ2BZM4s+1Z1aAE/JPof2E+dGebJ4Vor
            p9IGrXjkv7YpAEvQ+1gVT1zhaqXbfZmI+FnrSRAuSOVAaJBn9jXkmAO6kNpE92+g
            KLKXhNY5Op5uLiOVQv1ssvoDdvHaPh2JVq43KTz8qQucvsNSpER4JRDhPMmEoK4K
            7kadDhByfU2dgRxrvkjkOiIDUQo9q1f+ouot35UEtYNhB7ZtDK7aTyWlOKAohIsz
            EAzPXtF0emu+BNacyLVorAYL/jA0YZ+O1zHvVnzGD9V0uaDq7spp3XkOEM+TYTkk
            kf6gI25YhVzVxKOn0uD599Lkbo6AYg4nQvt6rey95w012+XUIkw2c2efmcNVyNo8
            Xx15vXheWwqV+/ewgFXczp5xOBJ1LMwytHhFNzumNLwC8g/y9ti8Qgn1IFrH9QhA
            NEwej60f244mOB3XBrVna0shqUav737kSZENod/sBUyH1gRdOU0wiqumPseE+szS
            UQEEl6eCtaeG/kJkRnv3OAVCNKarHcNryAeNgzK2EHRGZwQCjwP4FNIlsOetMCml
            tYhIAnGkl/o/Gtg8TmPmPpoBfcDdE2YRlKEyb13FJSGZNg==
            =OUWC
            -----END PGP MESSAGE-----
          fp: B9F81F327CF5346860E85269D7AF98F214C59E4E
        - created_at: "2023-02-02T11:09:14Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMAwDFOgk9tOQ+AQgAo7UeoLlh/4RcWwLYsfdu1FTwGFM8UGl/SBqh72Y6HgCt
            hjzUdDQLyAZppwg21oUPNt8RTGh94LtnM6DWpsiYqVDTQ5QjVRg3Pd3DbkusUKLs
            V5iIkRs4xhMW85metd+Rq715pUk/8wWaPi8hBHDSZFbKWL7e9BEQ6ilh75jBcY3K
            FIrX2x9/wimGztJkU8K3yZ8TOElV9ejqlN6gaHFjHWQgTAYjHTWYJlpaokOfmRKZ
            TspjHvzM6LGpSs543sQJcjh3esEuASumw8zgJjQXRFhOlXjNsci9aLJDgxWjIfVI
            XsK6j1nxIyTG0QMO+HmMuHi/HEATYyHXYub8305iINJeARHgTyRUgOjlm8hLVZF2
            FXzoJKzbmIUlMFwP4tOQSYVT8VT21Zo1LDj7MCU57n5NQZm81NihLxiO8sh3WltP
            knDqPpbfyN+Gxh8/+D9WkPh2/vGokjo2A/DArSGeUw==
            =XG84
            -----END PGP MESSAGE-----
          fp: 0600D41E1313E31016F7C55BF597BC0C5F22D1A2
    unencrypted_suffix: _unencrypted
    version: 3.7.3
