name: Terraform lint
on:
  pull_request:
    paths:
      - 'terraform/**'
      - '.tool-versions'
      - '.github/actions/**'
      - '.github/workflows/lint-terraform.yaml'
  push:
    branches:
      - master
    paths:
      - 'terraform/**'
      - '.tool-versions'
      - '.github/actions/**'
      - '.github/workflows/lint-terraform.yaml'

jobs:
  terraform-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: ./.github/actions/setup
      - name: Lint
        working-directory: ./terraform
        run: >
          terraform fmt --recursive --check --list=true --diff
